### PR TITLE
Fix support for ActiveRecord < 6

### LINKED ISSUE #59: Adding a foreign key causes `ArgumentError: unknown keyword: :column`
Hello 👋 

First of all thank you for sharing this very handy gem which works _out of the box_ and solves such a great pain 🙌 

**Problem**
I ran into an issue using the latest `1.3.0` version of the gem on a ruby `2.7.4` rails `5.2.6` project.
Adding a foreign key to a table with `add_reference` triggered an `ArgumentError: unknown keyword: :column` when running `rails db:migrate`. I reproduced the error on a vanilla [`rails new` project](https://github.com/Eschults/safe-pg-add-reference/commits/master) with the same versions to let you reproduce the 🐛  easily 👌 
Here is the backtrace 👇 

```bash
== 20211015145629 AddRestaurantReferenceToReviews: migrating ==================
-- add_reference(:reviews, :restaurant, {:foreign_key=>true})
   -> add_index("reviews", ["restaurant_id"], {:algorithm=>:concurrently})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

unknown keyword: :column
/Users/edwardschults/code/Eschults/safe-pg-add-reference/db/migrate/20211015145629_add_restaurant_reference_to_reviews.rb:3:in `change'
/Users/edwardschults/code/Eschults/safe-pg-add-reference/bin/rails:9:in `<top (required)>'
/Users/edwardschults/code/Eschults/safe-pg-add-reference/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'

Caused by:
ArgumentError: unknown keyword: :column
/Users/edwardschults/code/Eschults/safe-pg-add-reference/db/migrate/20211015145629_add_restaurant_reference_to_reviews.rb:3:in `change'
/Users/edwardschults/code/Eschults/safe-pg-add-reference/bin/rails:9:in `<top (required)>'
/Users/edwardschults/code/Eschults/safe-pg-add-reference/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

After debugging and `step`-ping in the source code, I found out that the error was coming from [this line](https://github.com/doctolib/safe-pg-migrations/blob/55a46708ef955e174b245a42a1ae78b404616433/lib/safe-pg-migrations/plugins/idempotent_statements.rb#L40), which [changed between `1.2.3` and `1.3.0`](https://github.com/doctolib/safe-pg-migrations/compare/v1.2.3...v1.3.0) with the addition of support for Ruby 3.0.

Note that when this error occurs, the creation of the column _actually goes through_, but not the creation of the `schema_migrations` record, making any new `rails db:migrate` run into the error again and preventing next migrations to run.

**Solution**
Downgrading to `1.2.3` solves the error on ruby 2.7 👌 

Cheers!

### PR DESCRIPTION
**Pull request by ThHareau**
Some methods have changed the number or argument between version 5.2 and version 6: 

`foreign_key_exists?` from

```rb
      def foreign_key_exists?(from_table, options_or_to_table = {})
```
https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1010

to 
```rb
      def foreign_key_exists?(from_table, to_table = nil, **options)
```
https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1151

And `validate_foreign_key` from 

```rb
        def validate_foreign_key(from_table, options_or_to_table = {})
```
https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L626

To

```rb
        def validate_foreign_key(from_table, to_table = nil, **options)
```
https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L603

--- 

This fixes #59 .

### CODE REVIEW

File: lib/safe-pg-migrations/plugins/old_rails_version_support.rb [hunk 1]
```diff
@@ -0,0 +1,23 @@
+# frozen_string_literal: true
+
+module SafePgMigrations
+  module OldRailsVersionSupport
+    ACTIVE_RECORD_VERSION = ActiveRecord::VERSION::STRING
+
+    ruby2_keywords def validate_foreign_key(from_table, to_table = nil, **options)
+      if ACTIVE_RECORD_VERSION < '6'
```
Comment (rchoquet) [inline lib/safe-pg-migrations/plugins/old_rails_version_support.rb:8]: You should not use a string for comparison, otherwise it will break starting from `'10'`

File: lib/safe-pg-migrations/base.rb [hunk 2]
```diff
@@ -17,6 +18,7 @@ module SafePgMigrations
     StatementRetrier,
     StatementInsurer,
     UselessStatementsLogger,
+    OldRailsVersionSupport,
```
Comment (rchoquet) [inline lib/safe-pg-migrations/base.rb:21]: More of a `LegacyActiveRecordSupport`?

File: lib/safe-pg-migrations/plugins/old_rails_version_support.rb (hunk 1 above)
Comment (ThHareau) [reply lib/safe-pg-migrations/plugins/old_rails_version_support.rb]: Fixed :)

**Review by rchoquet — APPROVED** [review]
